/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TopPanel.java
 *
 * Created on Oct 21, 2013, 8:02:21 PM
 */

package panels.design;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import newattendancesystem.MainFrame;

/**
 *
 * @author apex predator
 */
public class TopPanel extends javax.swing.JPanel {
    private Image image;
    private ImageIcon logUp;
    private ImageIcon logDown;
    private ImageIcon exitUp;
    private ImageIcon exitDown;
    private boolean login;
    private JFrame frame;
    
    /** Creates new form TopPanel */
    public TopPanel(JFrame frm) {
        initComponents();
        frame=frm;
        Toolkit toolkit= this.getToolkit();
    
        Class cls=getClass();
        try{
            int w=action.getWidth();
            int h=action.getHeight();
            //image=toolkit.getImage(cls.getResource("/image/topimage.jpeg").getPath().replaceAll("%20"," "));
            image=ImageIO.read(cls.getResource("/image/topimage.jpeg"));
            
            //Image temp=toolkit.getImage(cls.getResource("/image/navigator/logup.jpeg").getPath().replaceAll("%20"," "));
            Image temp=ImageIO.read(cls.getResource("/image/navigator/logup.jpeg"));
            temp=temp.getScaledInstance(w, h, Image.SCALE_DEFAULT);
            logUp=new ImageIcon(temp);

            //temp=toolkit.getImage(cls.getResource("/image/navigator/logdown.jpeg").getPath().replaceAll("%20"," "));
            temp=ImageIO.read(cls.getResource("/image/navigator/logdown.jpeg"));
            temp=temp.getScaledInstance(w, h, Image.SCALE_DEFAULT);
            logDown=new ImageIcon(temp);

            //temp=toolkit.getImage(cls.getResource("/image/navigator/exitup.jpg").getPath().replaceAll("%20"," "));
            temp=ImageIO.read(cls.getResource("/image/navigator/exitup.jpg"));
            temp=temp.getScaledInstance(w, h, Image.SCALE_DEFAULT);
            exitUp=new ImageIcon(temp);

            //temp=toolkit.getImage(cls.getResource("/image/navigator/exitdown.jpg").getPath().replaceAll("%20"," "));
            temp=ImageIO.read(cls.getResource("/image/navigator/exitdown.jpg"));
            temp=temp.getScaledInstance(w, h, Image.SCALE_DEFAULT);
            exitDown=new ImageIcon(temp);

            action.setIcon(exitUp);
        }catch(IOException e){
            
        }
        imageLbl.setIcon(null);
    }

    public void paint(Graphics g){
        super.paint(g);
        int h=this.getHeight();
        int w=this.getWidth();
        bckImage.setSize(w, h);
        Image scaledimage=image.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_DEFAULT);
        bckImage.setIcon(new ImageIcon(scaledimage));
        bckImage.revalidate();

        //int x=w-action.getWidth();
        int y=h-action.getHeight();
        action.setLocation(0, y);
        action.revalidate();
        
        
        int x=w-imageLbl.getWidth();
        imageLbl.setLocation(x, 0);
        this.revalidate();
        //System.out.println("Painted");
    }

    public void setProfileImage(Image image){
        if(image!=null){
            Toolkit toolkit= this.getToolkit();
            Image scaledImage=image.getScaledInstance(imageLbl.getWidth(), imageLbl.getHeight(), Image.SCALE_DEFAULT);
            imageLbl.setIcon(new ImageIcon(scaledImage));
            imageLbl.revalidate();
        }
    }
    
    public void loggedIn(){
        login=true;
        action.setIcon(logUp);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        action = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imageLbl = new javax.swing.JLabel();
        bckImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        action.setForeground(new java.awt.Color(102, 255, 102));
        action.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        action.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                actionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                actionMouseReleased(evt);
            }
        });
        add(action);
        action.setBounds(0, 160, 40, 40);

        jLabel3.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Shri Vaishnav Institute of Management");
        add(jLabel3);
        jLabel3.setBounds(70, 0, 620, 50);

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Affiliated by RGPV");
        add(jLabel4);
        jLabel4.setBounds(70, 50, 600, 19);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/svimi.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 70, 80);

        imageLbl.setForeground(new java.awt.Color(255, 255, 255));
        imageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/default.png"))); // NOI18N
        add(imageLbl);
        imageLbl.setBounds(660, 70, 110, 128);

        bckImage.setForeground(new java.awt.Color(51, 255, 51));
        add(bckImage);
        bckImage.setBounds(0, 0, 790, 200);
    }// </editor-fold>//GEN-END:initComponents

    private void actionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionMousePressed
        // TODO add your handling code here:
        if(login){
            action.setIcon(logDown);
        }else{
            action.setIcon(exitDown);
        }
    }//GEN-LAST:event_actionMousePressed

    private void actionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionMouseReleased
        // TODO add your handling code here:
        if(login){
            action.setIcon(logUp);
        }else{
            action.setIcon(exitUp);
        }
    }//GEN-LAST:event_actionMouseReleased

    private void actionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionMouseClicked
        // TODO add your handling code here:
        if(login){
            login=false;
            action.setIcon(exitUp);
            MainFrame.mainFrame.resetSystemUser();
            imageLbl.setIcon(null);
        }else{
            //new ProgressFrame("Closing",true,100,null).setVisible(true);
            frame.dispose();
        }
    }//GEN-LAST:event_actionMouseClicked


    public static void main(String ...s){
        JFrame frm=new JFrame();
        frm.add(new TopPanel(frm));
        frm.setVisible(true);
        frm.setSize(600, 200);
        frm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel action;
    private javax.swing.JLabel bckImage;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
