/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImportStudentPanel.java
 *
 * Created on Oct 22, 2013, 12:17:48 AM
 */

package panels;

import newattendancesystem.ProgressFrame;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Vector;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import sql.StudentSql;

/**
 *
 * @author Hemant Borade
 */
public class ImportStudentPanel extends javax.swing.JPanel implements PanelInterface{

    public int indexOfTab;
    private JComponent parent;
    private File importFile=null;
    //private static final int NO_OF_COL=11;
    private final String columns[]=new String[]{"Enrollmnet No","Name","Father's Name","Contact No","Email ID","Address","Class","Batch No","Semester","Section","Sr No"};
    private Vector data;

    /** Creates new form ImportStudentPanel */
    public ImportStudentPanel() {
        initComponents();
        parent=this;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        filePathTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jft1 = new javax.swing.JFormattedTextField();
        jft2 = new javax.swing.JFormattedTextField();
        jft3 = new javax.swing.JFormattedTextField();
        jft4 = new javax.swing.JFormattedTextField();
        jft5 = new javax.swing.JFormattedTextField();
        jft6 = new javax.swing.JFormattedTextField();
        jft7 = new javax.swing.JFormattedTextField();
        jft8 = new javax.swing.JFormattedTextField();
        jft9 = new javax.swing.JFormattedTextField();
        jft10 = new javax.swing.JFormattedTextField();
        jft11 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        text3 = new javax.swing.JTextField();
        text4 = new javax.swing.JFormattedTextField();
        text5 = new javax.swing.JTextField();
        text6 = new javax.swing.JTextField();
        text7 = new javax.swing.JTextField();
        text8 = new javax.swing.JTextField();
        text9 = new javax.swing.JTextField();
        text10 = new javax.swing.JTextField();
        text11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        headAvailable = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        sbmtBtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enrollment No", "Name", "Father's Name", "Contact No", "Email ID", "Address", "Class", "Batch no", "Semester", "Section", "Sr no"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentTable);

        jLabel19.setText("If Record Exists: ");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Update");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Ignore");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttonimage/SAVE.PNG"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 616, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Select File:");

        filePathTxt.setEditable(false);
        filePathTxt.setBackground(new java.awt.Color(204, 204, 204));
        filePathTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setLayout(new java.awt.GridLayout(4, 12, 5, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Field Name:");
        jPanel1.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enrollment No");
        jPanel1.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Father's Name");
        jPanel1.add(jLabel23);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Contact No");
        jPanel1.add(jLabel7);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Email ID");
        jPanel1.add(jLabel21);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Address");
        jPanel1.add(jLabel22);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Class");
        jPanel1.add(jLabel4);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Batch ");
        jPanel1.add(jLabel12);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Semester");
        jPanel1.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Section");
        jPanel1.add(jLabel6);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Sr No");
        jPanel1.add(jLabel11);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Column No:");
        jPanel1.add(jLabel8);

        jft1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jft1.setText("3");
        jft1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jft1ActionPerformed(evt);
            }
        });
        jPanel1.add(jft1);

        jft2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jft2.setText("1");
        jft2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jft2ActionPerformed(evt);
            }
        });
        jPanel1.add(jft2);

        jft3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jft3.setText("2");
        jft3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jft3ActionPerformed(evt);
            }
        });
        jPanel1.add(jft3);

        jft4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jft4.setText("6");
        jPanel1.add(jft4);

        jft5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jft5.setText("8");
        jft5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jft5ActionPerformed(evt);
            }
        });
        jPanel1.add(jft5);

        jft6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jft6.setText("7");
        jft6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jft6ActionPerformed(evt);
            }
        });
        jPanel1.add(jft6);

        jft7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jft7.setText("4");
        jPanel1.add(jft7);

        jft8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jft8.setText("9");
        jPanel1.add(jft8);

        jft9.setText("10");
        jPanel1.add(jft9);

        jft10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jft10.setText("5");
        jPanel1.add(jft10);

        jft11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jft11.setText("11");
        jPanel1.add(jft11);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Default Value:");
        jLabel9.setToolTipText("Default Value:");
        jPanel1.add(jLabel9);
        jPanel1.add(jLabel10);

        text2.setText("N.A.");
        text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text2ActionPerformed(evt);
            }
        });
        jPanel1.add(text2);

        text3.setText("NA");
        jPanel1.add(text3);

        text4.setText("1");
        jPanel1.add(text4);

        text5.setText("NA");
        jPanel1.add(text5);

        text6.setText("NA");
        text6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text6ActionPerformed(evt);
            }
        });
        jPanel1.add(text6);

        text7.setText("MCA");
        jPanel1.add(text7);

        text8.setText("2014");
        jPanel1.add(text8);

        text9.setText("6");
        jPanel1.add(text9);

        text10.setText("B");
        text10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text10ActionPerformed(evt);
            }
        });
        jPanel1.add(text10);

        text11.setText("0");
        jPanel1.add(text11);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Headings in File:");
        jLabel13.setToolTipText("Headings in File");
        jPanel1.add(jLabel13);

        headAvailable.setBackground(new java.awt.Color(255, 255, 255));
        headAvailable.setText("Available");
        jPanel1.add(headAvailable);
        jPanel1.add(jLabel14);
        jPanel1.add(jLabel15);
        jPanel1.add(jLabel26);
        jPanel1.add(jLabel16);
        jPanel1.add(jLabel17);
        jPanel1.add(jLabel24);
        jPanel1.add(jLabel25);

        sbmtBtn.setText("Import");
        sbmtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmtBtnActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 51));
        jLabel20.setText("Import Student Database");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sbmtBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filePathTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel20))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(filePathTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sbmtBtn))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //boolean complete;
        new Thread(new Runnable(){
            public void run(){
                int n=studentTable.getRowCount();
                //int n=1;
                if(n==0){
                    return;
                }
                boolean update=jRadioButton1.isSelected();
                ProgressFrame pf=new ProgressFrame(n-1,parent);
                pf.setVisible(true);
                StudentSql sql=new StudentSql(null);
                boolean inserted[]=new boolean[n];
                try{
                    sql.setAutoCommit(false);
                    pf.start();
                    for(int i=0;i<n;i++){
                        if(pf.value==-1){
                            throw (new Exception("Operation Cancelled"));
                            //JOptionPane.showMessageDialog(null, "Exception ");
                        }
                        pf.value=i;
                        String values[]=getStudentInfoFromTable(i);
                        inserted[i]=sql.insertStudent(values[0], values[1], values[6], Integer.parseInt(values[8]), values[9], Integer.parseInt(values[10]), values[2],values[4],values[3],values[5], Integer.parseInt(values[7]),update);
                        //sql.insertStudent("0807ca111001", "abc" ,"mca", 1, "A", 1,"fname" ,"email","1236547896","addr",2014, update);
                        Thread.sleep(100);
                    }
                    sql.commit();
                }catch(Exception e){
                    //JOptionPane.showMessageDialog(null, e.toString());
                    sql.rollback();
                    sql.close();
                    JOptionPane.showMessageDialog(null, e.toString());
                    e.printStackTrace();
                    return;
                    //complete=false;
                }
                sql.setAutoCommit(true);
                sql.close();
                //JOptionPane.showMessageDialog(null, "All Data Successfully saved.");
                for(int i=n-1;i>=0;i--){
                    if(inserted[i]){
                        ((DefaultTableModel)studentTable.getModel()).removeRow(i);
                    }
                }
            }
        }).start();
        //JOptionPane.showMessageDialog(this, "All Data Successfully saved.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc=new JFileChooser();
        fc.setAcceptAllFileFilterUsed(false);
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Excel Files(*.csv)",new String[]{"csv"}));
        fc.showOpenDialog(this);
        importFile=fc.getSelectedFile();
        if(importFile!=null){
            filePathTxt.setText(importFile.getAbsolutePath());
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jft3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jft3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jft3ActionPerformed

    private void jft5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jft5ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jft5ActionPerformed

    private void jft6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jft6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jft6ActionPerformed

    private void text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_text2ActionPerformed

    private void sbmtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtBtnActionPerformed
        // TODO add your handling code here:
        if(importFile==null){
            JOptionPane.showMessageDialog(this, "Please Select File");
            return;
        }
        //String val="";
        Component []components=jPanel1.getComponents();
        for(Component field:components){
            String cls=field.getClass().getName();
            //val= val+" , "+cls;
            if(cls.equalsIgnoreCase("javax.swing.JTextField") || cls.equalsIgnoreCase("javax.swing.JFormattedTextField")) {
                if(((JTextField)field).getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Please fill all Fields.");
                    break;
                }
            }
        }
        int index[]=new int[columns.length];
        index[0]=Integer.parseInt(jft1.getText());
        index[1]=Integer.parseInt(jft2.getText());
        index[2]=Integer.parseInt(jft3.getText());
        index[3]=Integer.parseInt(jft4.getText());
        index[4]=Integer.parseInt(jft5.getText());
        index[5]=Integer.parseInt(jft6.getText());
        index[6]=Integer.parseInt(jft7.getText());
        index[7]=Integer.parseInt(jft8.getText());
        index[8]=Integer.parseInt(jft9.getText());
        index[9]=Integer.parseInt(jft10.getText());
        index[10]=Integer.parseInt(jft11.getText());


        String def[]=new String[columns.length];
        def[0]="";
        def[1]=text2.getText();
        def[2]=text3.getText();
        def[3]=text4.getText();
        def[4]=text5.getText();
        def[5]=text6.getText();
        def[6]=text7.getText();
        def[7]=text8.getText();
        def[8]=text9.getText();
        def[9]=text10.getText();
        def[10]=text11.getText();
        
        try{
            getValues(index,def);
            setValues();
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.toString());
        }

        //JOptionPane.showMessageDialog(this, val);
}//GEN-LAST:event_sbmtBtnActionPerformed

    private void jft1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jft1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jft1ActionPerformed

    private void jft2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jft2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jft2ActionPerformed

    private void text6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text6ActionPerformed

    private void text10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text10ActionPerformed

    private void getValues(int indx[],String def[]) throws IOException{
        //Vector data=new Vector();
        data=new Vector();
        BufferedReader br=null;
        br=new BufferedReader(new FileReader(importFile));
        String line=null;
        /*for(int n=Integer.parseInt(jFormattedTextField9.getText());n>0;n--){
            br.readLine();
        }*/
        if(headAvailable.isSelected()){
            line=br.readLine();
        }
        //System.out.println(line);
        while((line=br.readLine())!=null){
            //System.out.println(line);
            String val[]=line.split(",");
            //if(val.length==NO_OF_COL-1){
                Vector values=new Vector();
                for(int i=0;i<columns.length;i++){
                    try{
                        String temp=val[indx[i]-1].replaceAll("\"", "");
                        if(temp.equals("")){
                            values.addElement(def[i]);
                            //cls=def[i];
                        }else{
                            values.addElement(temp);
                            //cls=temp;
                        }
                    }catch(ArrayIndexOutOfBoundsException e){
                         e.printStackTrace();
                    }
                }
                /*String temp=val[indx[0]-1];  //Enrollment No
                if(temp.length()!=12){
                   values.addElement("Incorrect Eno");
                }else{
                    String cls=null;
                    if(val[indx[2]-1].equalsIgnoreCase("")){
                        cls=def[2];
                    }else{
                        cls=val[indx[2]-1];
                    }
                    if(cls.equalsIgnoreCase("MCA")){
                        values.addElement(Integer.parseInt("20"+temp.substring(6, 8))+3);
                    }else{
                        values.addElement(cls);
                    }*/
              //  }
            //System.out.println(values);
            data.addElement(values);
            }
        if(br!=null){
            br.close();
        }
        //return data;
    }

    private void setValues(){
        Vector col=new Vector();
        for(int i=0;i<columns.length;i++){
            col.addElement(columns[i]);
        }
        DefaultTableModel tm=new DefaultTableModel(data,col);
        studentTable.setModel(tm);
        studentTable.setAutoCreateRowSorter(true);
        this.revalidate();
    }

    private void setSection(){

    }

    private void setSrNo(){

    }

    private String[] getStudentInfoFromTable(int index){
        String info[]=new String[columns.length];
        for(int i=0;i<info.length;i++){
            info[i]=studentTable.getValueAt(index, i).toString();
        }
        return info;
    }

    public boolean destroy(){
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField filePathTxt;
    private javax.swing.JCheckBox headAvailable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jft1;
    private javax.swing.JFormattedTextField jft10;
    private javax.swing.JFormattedTextField jft11;
    private javax.swing.JFormattedTextField jft2;
    private javax.swing.JFormattedTextField jft3;
    private javax.swing.JFormattedTextField jft4;
    private javax.swing.JFormattedTextField jft5;
    private javax.swing.JFormattedTextField jft6;
    private javax.swing.JFormattedTextField jft7;
    private javax.swing.JFormattedTextField jft8;
    private javax.swing.JFormattedTextField jft9;
    private javax.swing.JButton sbmtBtn;
    private javax.swing.JTable studentTable;
    private javax.swing.JTextField text10;
    private javax.swing.JTextField text11;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JFormattedTextField text4;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text6;
    private javax.swing.JTextField text7;
    private javax.swing.JTextField text8;
    private javax.swing.JTextField text9;
    // End of variables declaration//GEN-END:variables

}
