/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.report;

import component.CustomDialog;
import java.awt.Cursor;
import java.awt.Graphics2D;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import newattendancesystem.MainFrame;
import panels.CompiledAttendanceView;
import panels.ViewAttendance;
import report.handler.Schedule;
import report.handler.StudentReport;

/**
 *
 * @author yash
 */
public class AdminReportPanel extends javax.swing.JPanel {

    private static int height=375;
    
    private static String ATTNDNC_CMPIL="/image/reportsnapshot/attendancecompile.JPG";
    private static String ATTNDNC_DETAIL="/image/reportsnapshot/attendancedaily.JPG";
    private static String STUDENT_REPORT="/image/reportsnapshot/student.JPG";
    private static String FACULTY_REPORT="/image/reportsnapshot/faculty.JPG";
    private static String FACULTY_TIMETABLE="/image/reportsnapshot/facultytimetable.JPG";
    private static String CLASS_TIMETABLE="/image/reportsnapshot/timetable.JPG";
    
    private int selected;
    private Toolkit toolkit;
    /**
     * Creates new form AdminReportPanel
     */
    public AdminReportPanel() {
        initComponents();
        toolkit= this.getToolkit();
        int type;
        BufferedImage originalImage;
        try {
            originalImage=ImageIO.read(AdminReportPanel.class.getResource(CLASS_TIMETABLE));
            type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
            //System.out.println(jLabel1.getWidth()+"  "+ jLabel1.getHeight());
            jLabel1.setIcon(new ImageIcon(resizeImage(originalImage, type, 270, 190)));
            
            originalImage=ImageIO.read(AdminReportPanel.class.getResource(FACULTY_TIMETABLE));
            type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
            //System.out.println(jLabel1.getWidth()+"  "+ jLabel1.getHeight());
            jLabel2.setIcon(new ImageIcon(resizeImage(originalImage, type, 250, 190)));
            
            originalImage=ImageIO.read(AdminReportPanel.class.getResource(STUDENT_REPORT));
            type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
            //System.out.println(jLabel1.getWidth()+"  "+ jLabel1.getHeight());
            jLabel3.setIcon(new ImageIcon(resizeImage(originalImage, type, 270, 190)));
            
            originalImage=ImageIO.read(AdminReportPanel.class.getResource(FACULTY_REPORT));
            type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
            //System.out.println(jLabel1.getWidth()+"  "+ jLabel1.getHeight());
            jLabel4.setIcon(new ImageIcon(resizeImage(originalImage, type, 170, 190)));
            
            originalImage=ImageIO.read(AdminReportPanel.class.getResource(ATTNDNC_DETAIL));
            type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
            //System.out.println(jLabel1.getWidth()+"  "+ jLabel1.getHeight());
            jLabel9.setIcon(new ImageIcon(resizeImage(originalImage, type, 170, 190)));
            
            originalImage=ImageIO.read(AdminReportPanel.class.getResource(ATTNDNC_CMPIL));
            type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
            //System.out.println(jLabel1.getWidth()+"  "+ jLabel1.getHeight());
            jLabel11.setIcon(new ImageIcon(resizeImage(originalImage, type, 270, 190)));
            
            jLabel1MouseClicked(null);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    private static BufferedImage resizeImage(BufferedImage originalImage, int type,int width,int height){
	BufferedImage resizedImage = new BufferedImage(width, height, type);
	Graphics2D g = resizedImage.createGraphics();
	g.drawImage(originalImage, 0, 0, width, height, null);
	g.dispose();
 
	return resizedImage;
    }
    
    private Image scaleImage(Image image,int width,int height){
        return image.getScaledInstance(width, height, Image.SCALE_DEFAULT);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bigImage = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttonimage/exit_Hover.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel13, org.openide.util.NbBundle.getMessage(AdminReportPanel.class, "AdminReportPanel.jLabel13.text")); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(882, 882, 882)
                .addComponent(jLabel13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AdminReportPanel.class, "AdminReportPanel.jLabel1.text")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(AdminReportPanel.class, "AdminReportPanel.jLabel2.text")); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(AdminReportPanel.class, "AdminReportPanel.jLabel3.text")); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(AdminReportPanel.class, "AdminReportPanel.jLabel4.text")); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(AdminReportPanel.class, "AdminReportPanel.jLabel5.text")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(AdminReportPanel.class, "AdminReportPanel.jLabel6.text")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(AdminReportPanel.class, "AdminReportPanel.jLabel7.text")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(AdminReportPanel.class, "AdminReportPanel.jLabel8.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(AdminReportPanel.class, "AdminReportPanel.jLabel9.text")); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(AdminReportPanel.class, "AdminReportPanel.jLabel10.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(AdminReportPanel.class, "AdminReportPanel.jLabel11.text")); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(AdminReportPanel.class, "AdminReportPanel.jLabel12.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        org.openide.awt.Mnemonics.setLocalizedText(bigImage, org.openide.util.NbBundle.getMessage(AdminReportPanel.class, "AdminReportPanel.bigImage.text")); // NOI18N
        bigImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bigImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bigImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bigImage)
                .addGap(426, 426, 426))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(bigImage, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
        );

        jScrollPane1.getViewport().setOpaque(false);
        jPanel2.setLayout(new GridBagLayout());
        jPanel2.add(bigImage);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        try{
            selected=1;
            BufferedImage originalImage=ImageIO.read(AdminReportPanel.class.getResource(CLASS_TIMETABLE));
            int type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
            //System.out.println(jLabel1.getWidth()+"  "+ jLabel1.getHeight());
            bigImage.setIcon(new ImageIcon(resizeImage(originalImage, type, 450, height)));
            //bigImage.setIcon(new ImageIcon(AdminReportPanel.class.getResource(CLASS_TIMETABLE)));
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        MainFrame.glassPane.destroy();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        try{
            selected=2;
            BufferedImage originalImage=ImageIO.read(AdminReportPanel.class.getResource(FACULTY_TIMETABLE));
            int type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
            //System.out.println(jLabel1.getWidth()+"  "+ jLabel1.getHeight());
            bigImage.setIcon(new ImageIcon(resizeImage(originalImage, type, 450, height)));
            //bigImage.setIcon(new ImageIcon(AdminReportPanel.class.getResource(CLASS_TIMETABLE)));
        }catch(Exception e){
            e.printStackTrace();
        }
        //bigImage.setIcon(new ImageIcon(AdminReportPanel.class.getResource(FACULTY_TIMETABLE)));
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        try{
            selected=3;
            BufferedImage originalImage=ImageIO.read(AdminReportPanel.class.getResource(STUDENT_REPORT));
            int type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
            //System.out.println(jLabel1.getWidth()+"  "+ jLabel1.getHeight());
            bigImage.setIcon(new ImageIcon(resizeImage(originalImage, type, 450, height)));
            //bigImage.setIcon(new ImageIcon(AdminReportPanel.class.getResource(CLASS_TIMETABLE)));
        }catch(Exception e){
            e.printStackTrace();
        }
        //bigImage.setIcon(new ImageIcon(AdminReportPanel.class.getResource(STUDENT_REPORT)));
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        try{
            selected=4;
            BufferedImage originalImage=ImageIO.read(AdminReportPanel.class.getResource(FACULTY_REPORT));
            int type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
            //System.out.println(jLabel1.getWidth()+"  "+ jLabel1.getHeight());
            bigImage.setIcon(new ImageIcon(resizeImage(originalImage, type, 275, height)));
            //bigImage.setIcon(new ImageIcon(AdminReportPanel.class.getResource(CLASS_TIMETABLE)));
        }catch(Exception e){
            e.printStackTrace();
        }
        //bigImage.setIcon(new ImageIcon(AdminReportPanel.class.getResource(FACULTY_REPORT)));
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        try{
            selected=9;
            BufferedImage originalImage=ImageIO.read(AdminReportPanel.class.getResource(ATTNDNC_DETAIL));
            int type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
            //System.out.println(jLabel1.getWidth()+"  "+ jLabel1.getHeight());
            bigImage.setIcon(new ImageIcon(resizeImage(originalImage, type, 275, height)));
            //bigImage.setIcon(new ImageIcon(AdminReportPanel.class.getResource(CLASS_TIMETABLE)));
        }catch(Exception e){
            e.printStackTrace();
        }
        //bigImage.setIcon(new ImageIcon(AdminReportPanel.class.getResource(ATTNDNC_DETAIL)));
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       // TODO add your handling code here:
        try{
            selected=11;
            BufferedImage originalImage=ImageIO.read(AdminReportPanel.class.getResource(ATTNDNC_CMPIL));
            int type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
            //System.out.println(jLabel1.getWidth()+"  "+ jLabel1.getHeight());
            bigImage.setIcon(new ImageIcon(resizeImage(originalImage, type, 450, height)));
            //bigImage.setIcon(new ImageIcon(AdminReportPanel.class.getResource(CLASS_TIMETABLE)));
        }catch(Exception e){
            e.printStackTrace();
        }
        //bigImage.setIcon(new ImageIcon(AdminReportPanel.class.getResource(ATTNDNC_CMPIL)));
    }//GEN-LAST:event_jLabel11MouseClicked

    private void bigImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bigImageMouseClicked
        // TODO add your handling code here:
        new Thread(){

            @Override
            public void run() {
                Cursor old=bigImage.getCursor();
                MainFrame.mainFrame.startProcessing("Generating");
                bigImage.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                switch(selected){
                    case 1://class time table report
                        ClassSelectionPanel e=new ClassSelectionPanel();
                        int option=JOptionPane.showOptionDialog(AdminReportPanel.this, e, "Select Class", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, new String[]{"Generate"}, null);
                        if(option==JOptionPane.OK_OPTION){
                            Schedule sr=new Schedule();
                            sr.generateTimeTable(e.cls,e.sem, e.section, null);
                        }
                    break;
                    case 2://Faculty Time table report
                        new report.handler.FacultyReport().generateFacultyTimeTable();
                        break;
                    case 3://student report
                        StudentReportPanel e2=new StudentReportPanel();
                        int option2=JOptionPane.showOptionDialog(AdminReportPanel.this, e2, "Select Class", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, new String[]{"Generate"}, null);
                        if(option2==JOptionPane.OK_OPTION){
                            StudentReport sr=new StudentReport();
                            sr.studentReport(e2.cls,e2.bno, e2.sem,e2.section);
                        }
                        break;
                    case 4://faculty report
                        new report.handler.FacultyReport().generateFacultyReport();
                        break;
                    case 9://attendance details
                        new CustomDialog(MainFrame.mainFrame, true, new ViewAttendance(), "Attendance Details").setVisible(true);
                        break;
                    case 11://attendance compilation
                        new CustomDialog(MainFrame.mainFrame, true, new CompiledAttendanceView(), "Attendance Details").setVisible(true);
                        break;
                }
                bigImage.setCursor(old);
                MainFrame.mainFrame.stopProcessing();
            }
            
        }.start();
        
        
    }//GEN-LAST:event_bigImageMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bigImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
