/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package component;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author yash
 */
public class FacultySelectionOption extends javax.swing.JPanel {

    ArrayList<JCheckBox> list;
    /**
     * Creates new form FacultySelectionOption
     */
    public FacultySelectionOption(String []fname,String []selected,boolean single) {
        initComponents();
        //jLabel2.setText(scode);
        ButtonGroup grp=null;
        if(single){
            grp=new ButtonGroup();
        }
        list=new ArrayList<>(fname.length);
        JCheckBox temp;
        for(int i=0;i<fname.length;i++){
            temp=new JCheckBox(fname[i]);
            if(grp!=null){
                grp.add(temp);
            }
            for(int j=0;j<selected.length;j++){
                if(fname[i].equalsIgnoreCase(selected[j])){
                    temp.setSelected(true);
                    break;
                }
            }
            list.add(temp);
            jPanel1.add(temp);
        }
    }

    public String[] getSelected(){
        String str=null;
        for(JCheckBox chk:list){
            if(chk.isSelected()){
                if(str==null){
                    str=chk.getText();
                }else{
                    str=str+":"+chk.getText();
                }
            }
        }
        if(str==null){
            return null;
        }
        return str.split(":");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(FacultySelectionOption.class, "FacultySelectionOption.jLabel3.text")); // NOI18N

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /*public static void main(String arg[]){
        new TestFrame(new FacultySelectionOption(new String[]{"A","B","C"},new String[]{"A","c"}, false));
    }*/
}
